version: "3.7"

services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - neo4j
    environment:
      RESOURCES_PATH: /app/resources
      PROCESSED_PATH: /app/resources/processed
      MODEL_PATH: /app/resources/model
      UPLOADS_PATH: /app/resources/uploads
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    networks:
      - lateralvision

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    networks:
      - lateralvision

networks:
  lateralvision:
    driver: bridge
